// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type AuthPayload struct {
	User *User `json:"user"`
}

type BasicResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type GetUser struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	Email       string  `json:"email"`
	AccountType string  `json:"account_type"`
	EndingDate  *string `json:"ending_date,omitempty"`
}

type GetUserInfoResponse struct {
	Success bool     `json:"success"`
	Message string   `json:"message"`
	User    *GetUser `json:"user,omitempty"`
}

type LoginResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Mutation struct {
}

type PresignedURL struct {
	URL       string `json:"url"`
	Key       string `json:"key"`
	ExpiresAt string `json:"expiresAt"`
}

type Query struct {
}

type Track struct {
	ID        uuid.UUID  `json:"id"`
	AlbumID   *uuid.UUID `json:"albumId,omitempty"`
	Title     string     `json:"title"`
	Artist    *string    `json:"artist,omitempty"`
	Genre     *string    `json:"genre,omitempty"`
	Duration  *int32     `json:"duration,omitempty"`
	FileSize  *int32     `json:"fileSize,omitempty"`
	Format    *string    `json:"format,omitempty"`
	Key       string     `json:"key"`
	CreatedAt string     `json:"createdAt"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
